In [3]:
import numpy as np

In [4]:
# 1.buat vector x dengan ukuran 3x1
x = np.array([13, 8, 6]) # type argument is optional, e.g.: dtype=np.float16
x

array([13,  8,  6])

In [5]:
# hitung panjang vector x
len(x)

3

In [6]:
# tampilkan ukuran vector x
x.shape

(3,)

In [7]:
# tampilkan tipe data dari vector x
type(x)

numpy.ndarray

In [8]:
# akses elemen pertama dari vector x
x[0] # zero-indexed

np.int64(13)

In [9]:
# tampilkan tipe data elemen pertama dari vector x
type(x[0])

numpy.int64

In [10]:
# lakukan transpose pada vector x dan simpan pada variabel x_t
x_t = x.T
x_t

array([13,  8,  6])

In [11]:
# tampilkan ukuran dari vector x_t
x_t.shape

(3,)

In [12]:
y = np.array([[13, 8, 6]])
y

array([[13,  8,  6]])

In [13]:
# lakukan transpose pada vector y dan simpan pada variabel y_t
y_t = y.T
y_t


array([[13],
       [ 8],
       [ 6]])

In [15]:
# tampilkan ukuran dari vector x_t
y_t.shape

(3, 1)

In [16]:
# lakukan soal nomor 2 menggunakan pytorch dan tensorflow
import torch
import tensorflow as tf

In [17]:
x_pt = torch.tensor([13, 8, 6])
x_pt

tensor([13,  8,  6])

In [18]:
x_tf = tf.Variable([13, 8, 6])
x_tf

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([13,  8,  6], dtype=int32)>